# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'searsonApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '8.0'
  use_frameworks!
  pod 'Charts'

  # Pods for searsonApp

end

target 'watchApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchApp

end

target 'watchApp Extension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchApp Extension

end
